sonar.projectKey=berehx_teachua-deployment
sonar.organization=berehx
sonar.host.url=https://sonarcloud.io

sonar.sources=backend,frontend
sonar.sourceEncoding=UTF-8
sonar.java.binaries=backend

sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/db_data/**
