name: Build, Scan, and Deploy

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/teachua-backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/teachua-frontend:latest

  deploy:
    needs: build-scan-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd /home/azureuser/teachua-deployment
            sudo rm -rf db_data/
            git fetch origin feat/splunk-integration
            git reset --hard origin/feat/splunk-integration
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
            echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" >> .env
            echo "SPLUNK_TOKEN=${{ secrets.SPLUNK_TOKEN }}" >> .env
            echo "SPLUNK_URL=${{ secrets.SPLUNK_URL }}" >> .env
            sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d --force-recreate
